spring.application.name=EmployeeManagementSystem

# MySQL Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/employee-management-system
spring.datasource.username=root
spring.datasource.password=221902149

# Hibernate Properties
# 'update' will create/update tables automatically based on your Entity classes
spring.jpa.hibernate.ddl-auto=update

# Optional: Shows SQL queries in the console for debugging
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

#Security Config
#spring.security.user.name=fahad
#spring.security.user.password=123
jwt.secretKey=mySuperSecretKeyForEmployeeManagementSystem2026Appo